In [110]:
import sys,os
sys.path.append(os.pardir)
import reversi.reversi as rev
import numpy as np
import torch
import torch.nn as nn
import MCTS as M

import importlib

# モジュールの変更を反映
importlib.reload(rev)
importlib.reload(M)

<module 'MCTS' from '/Users/haruni20/Desktop/BoardGames/Othello/alphazero/MCTS.py'>

In [118]:
board = rev.Board()
MCTS = M.MCTS()

In [119]:
print(board)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [122]:
rate = MCTS.search(board, 50)

In [123]:
rate

[0.4, 0.5, 0.44, 0.38]