In [68]:
import sys,os
sys.path.append(os.pardir)
from copy import deepcopy
import reversi.reversi as rev
import numpy as np
import torch
import torch.nn as nn
import json

import MCTS as M

import importlib

# モジュールの変更を反映
importlib.reload(rev)
importlib.reload(M)

<module 'MCTS' from '/Users/haruni20/Desktop/BoardGames/Othello/alphazero/MCTS.py'>

In [69]:
board = rev.Board()
MCTS = M.MCTS()

In [96]:
print(board)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0 -1 -1 -1  1  0  0  0]
 [ 0  0  0 -1  1  1  1  1]
 [ 0 -1  0  1  0  1  0  0]
 [ 0  0 -1 -1  0  1  0  0]
 [ 0  0  0 -1  0  0  0  0]]


In [95]:
board.push(MCTS.search(board, 50))

In [ ]:
board.reset()
while board.end==False:
    if board.turn==rev.BLACK:
        board.push(MCTS.search(board, 100))
    else:
        board.push(np.random.choice(board.legal_moves))
    print(board)

In [25]:
a = np.array([1,5,5,5,3,2,1])

In [31]:
np.random.choice(np.argwhere(a==min(a)).flatten())

6

In [15]:
for i in range(46):
    del a[chr(i+65)]

In [16]:
a

{'aiueo': 1, 'kakikukeko': 2, 'aiueao': 0}