In [11]:
import sys,os
sys.path.append(os.pardir)
import reversi.reversi as rev
import numpy as np
import torch
import torch.nn as nn

import MCTS as M

import importlib

# モジュールの変更を反映
importlib.reload(rev)
importlib.reload(M)

<module 'MCTS' from '/Users/haruni20/Desktop/BoardGames/Othello/alphazero/MCTS.py'>

In [12]:
board = rev.Board()
MCTS = M.MCTS()

In [17]:
print(board)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0]
 [ 0  0  1  0  0 -1  0  0]
 [ 0  0  1  1 -1  0  0  0]
 [ 0  0  1  1 -1  0  0  0]
 [ 0  0  1  1 -1  1  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [16]:
for i in range(10):
    board.push(MCTS.search(board, 50))