In [1]:
import sys,os
sys.path.append(os.pardir)
from copy import deepcopy
import reversi.reversi as rev
from reversi.common import *
import numpy as np
import torch
import torch.nn as nn

from network import PolicyNet
import MCTS as M

import importlib

# モジュールの変更を反映
importlib.reload(rev)
importlib.reload(M)

<module 'MCTS' from '/Users/haruni20/Desktop/BoardGames/Othello/alphazero/MCTS.py'>

In [2]:
board = rev.Board()
MCTS = M.MCTS()
policy_net = PolicyNet()

In [3]:
policy_net.forward(torch.from_numpy(board.get_state()))

tensor([[ 0.1925,  0.0448,  0.0932,  0.0371, -0.1715,  0.0221,  0.0637, -0.0411,
         -0.0730,  0.0610,  0.0089,  0.0032, -0.3734,  0.0569,  0.1689,  0.2464,
          0.0365, -0.2534, -0.0966,  0.0667, -0.0439, -0.2154, -0.1580, -0.1060,
          0.2615, -0.1473, -0.0447,  0.0101,  0.0157,  0.0584, -0.0380,  0.2306,
          0.0435, -0.0121,  0.2632,  0.1373,  0.0509, -0.0319, -0.1372,  0.0390,
         -0.0870,  0.2943,  0.0351, -0.2969,  0.1460,  0.2484, -0.0228, -0.3059,
          0.0522,  0.0016,  0.0516, -0.0895, -0.2834, -0.0841,  0.0274, -0.1031,
          0.0973, -0.3123,  0.2120, -0.2006, -0.1140, -0.0104,  0.2536,  0.1655]],
       grad_fn=<AddmmBackward0>)

In [4]:
MCTS.search(board, 50).lower()

'c4'

In [ ]:
MCTS = M.MCTS()
board.reset()
while board.end==False:
    if board.turn==rev.BLACK:
        board.push(MCTS.search(board, 100))
    else:
        board.push(np.random.choice(board.legal_moves))
    print(board)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1 -1  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0 -1  1 -1  0  0]
 [ 0  0  0  1  1  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0 -1  1 -1  0  0]
 [ 0  0  0 -1 -1  1  0  0]
 [ 0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1  1 -1  0  0]
 [ 0  0  1  1  1  1  0  

In [7]:
x_train,y_train = MCTS.prepare_data()
x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)

In [8]:
y_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])